# Generated by Django 4.2.4 on 2023-08-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='serivceImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service',
            new_name='service_title',
        ),
        migrations.AddField(
            model_name='services',
            name='serivce_image1',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='serivce_image2',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='serivce_image3',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='serivce_image4',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='services',
            name='service_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
