# Generated by Django 4.2.4 on 2023-08-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_rename_service_description_services_service_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_title1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title4',
            field=models.CharField(max_length=50),
        ),
    ]
