# Generated by Django 4.2.4 on 2023-08-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_services_service_title1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='serivce_image1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serivce_image2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serivce_image3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serivce_image4',
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
