# Generated by Django 4.2.4 on 2023-08-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
    ]
