# Generated by Django 4.2.4 on 2023-08-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_blogimage_blog_blogimage1_remove_blog_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
