# Generated by Django 4.2.4 on 2023-08-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_blog_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author1',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blogImage1',
            new_name='blogImage',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='author2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='author3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blogImage2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blogImage3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='title12',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='title3',
        ),
    ]
