# Generated by Django 4.2.4 on 2023-08-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0005_rename_description_team_description1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbouUs',
        ),
    ]
