# Generated by Django 4.2.4 on 2023-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='productImage1',
        ),
        migrations.AddField(
            model_name='product',
            name='productImage2',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='productImage3',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
    ]
