# Generated by Django 4.2.4 on 2023-08-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rename_service_description_services_service_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='serivce_image1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serivce_image2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serivce_image3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serivce_image4',
        ),
    ]
