# Generated by Django 4.2.4 on 2023-08-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_services_serivce_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('help_type1', models.CharField(max_length=50)),
                ('help_type2', models.CharField(max_length=50)),
                ('help_type3', models.CharField(max_length=50)),
                ('help_type4', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
