# Generated by Django 4.2.4 on 2023-08-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_help_alter_services_service_title1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='Image1',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='help',
            name='Image2',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='help',
            name='Image3',
            field=models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to=''),
        ),
    ]
