# Generated by Django 4.2.4 on 2023-08-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_help_image1_help_image2_help_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PouplarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to='')),
            ],
        ),
    ]
