# Generated by Django 4.2.4 on 2023-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_rename_image_testimonials_image1_testimonials_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=15)),
                ('author1', models.CharField(max_length=15)),
                ('blogImage1', models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to='')),
                ('title12', models.CharField(max_length=15)),
                ('author2', models.CharField(max_length=15)),
                ('blogImage2', models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to='')),
                ('title3', models.CharField(max_length=15)),
                ('author3', models.CharField(max_length=15)),
                ('blogImage3', models.ImageField(blank=True, max_length=10000000000000, null=True, upload_to='')),
            ],
        ),
    ]
