# Generated by Django 4.2.4 on 2023-08-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title12',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title3',
            field=models.CharField(max_length=50),
        ),
    ]
