# Generated by Django 4.2.4 on 2023-08-18 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_post_author1_alter_post_author2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productImage1',
            new_name='productImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImage3',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
