# Generated by Django 4.2.4 on 2023-08-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_description1',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_title1',
            new_name='service_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_description2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_description3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_description4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_title2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_title3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_title4',
        ),
    ]
