# Generated by Django 4.2.4 on 2023-08-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_rename_service_description_services_service_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author1',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='blogImage1',
            new_name='blogImage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogImage2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogImage3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title12',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title3',
        ),
    ]
