# Generated by Django 4.2.4 on 2023-08-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_rename_author1_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbouUs',
        ),
    ]
