# Generated by Django 4.2.4 on 2023-08-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hadeer',
        ),
    ]
